name: Sync Race Logs to Grafana
on:
  push:
    paths:
      - 'data/*.csv'

jobs:
  sync-telemetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: pip install pandas requests
        
      - name: Push to Grafana Cloud
        env:
          GRAFANA_USER: "2396063"
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
          GRAFANA_URL: "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/v1/push/influx/write"
        run: python scripts/upload_to_grafana.py
